# Generated by Django 5.1.2 on 2025-01-13 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="assigned_to",
        ),
    ]
