# Generated by Django 5.1.2 on 2025-01-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_customuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.RenameField(
            model_name="project",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.RemoveField(
            model_name="project",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(default="Incomplete", max_length=50),
        ),
    ]
